model = {
r'^ix?[\d]{2,3}$': 're.sub',
r'^c-elysee$': '1',
r'^c-crosser$': '2',
r'^(Ka|Evo|Pro|Rio|One|Eos|up|New|Fe|Fox|Mii)$': '3',
r'^Top$': '4',
r'^allroad$': '5',
r'^quattro$': '6',
r'^X-Trail$': '7',
r'^Vel$': '8',
r'^Octavia5$': '9',
r'^i?[\d]{1,2}$': '10',
r'^mito$': '11',
r'^streetka$': '12',
r'^(IX|IV|V?I{0,3})$': '13',
r'^X-PERIENCE$': '14',
};